# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevinoAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('result', jsonfield.fields.JSONField(blank=True, null=True)),
                ('is_fail', models.BooleanField(default=False)),
                ('dc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevinoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_resource', models.CharField(choices=[('get_addresses_sender', 'get_addresses_sender'), ('add_address_sender', 'add_address_sender'), ('del_address_sender', 'del_address_sender'), ('get_bulk_list', 'get_bulk_list'), ('get_bulk', 'get_bulk'), ('add_bulk', 'add_bulk'), ('edit_bulk', 'edit_bulk'), ('edit_bulk_status', 'edit_bulk_status'), ('get_template', 'get_template'), ('add_template', 'add_template'), ('edit_template', 'edit_template'), ('del_template', 'del_template'), ('get_state', 'get_state'), ('get_state_detailing', 'get_state_detailing'), ('send_message', 'send_message'), ('get_status_message', 'get_status_message')], max_length=64)),
                ('data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('dc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='devinoanswer',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devino_answer', to='core.DevinoRequest'),
        ),
    ]
